import difflib
import unittest
from unittest.mock import patch

from parsimony.analysis import generated, implementation, measure, parse_patch
from parsimony.benchmark import analyze_submission, leaderboard
from tests.test_languages import HAS_LANGUAGES


def diff(before, after, path):
    return ''.join(difflib.unified_diff(before.splitlines(keepends=True), after.splitlines(keepends=True),
                                       fromfile='a/' + path if before else '/dev/null', tofile='b/' + path))


class LanguageScopeTests(unittest.TestCase):
    def test_language_scope_and_exclusions(self):
        for lang, paths in {'javascript': ['src/a.js', 'index.mjs', 'ui.jsx', 'src/a.ts', 'ui.tsx'],
                            'typescript': ['src/a.ts', 'ui.tsx', 'src/a.js'],
                            'go': ['main.go', 'pkg/a.go']}.items():
            for path in paths:
                self.assertTrue(implementation(path, lang), (path, lang))
                self.assertFalse(implementation(path))
        for path in ['src/a.test.ts', 'src/a.spec.tsx', '__tests__/a.ts', 'types/a.d.ts',
                     'node_modules/x/a.ts', 'generated/a.ts', 'src/api.generated.ts',
                     'src/schema.generated.js', 'docs/a.ts', 'tests/a.ts']:
            self.assertFalse(implementation(path, 'typescript'), path)
        for path in ['main_test.go', 'x.pb.go', 'x_generated.go', 'testdata/main.go']:
            self.assertFalse(implementation(path, 'go'), path)
        with self.assertRaises(ValueError):
            implementation('src/x.rs', 'rust')

    def test_generated_headers(self):
        self.assertTrue(generated('// Code generated by protoc. DO NOT EDIT.\npackage x\n', 'go'))
        self.assertTrue(generated('/* Auto-generated file */\nconst x = 1;\n', 'javascript'))
        self.assertTrue(generated('// @generated\nconst x = 1;\n', 'typescript'))
        self.assertFalse(generated('const text = "generated by a user";', 'javascript'))

    def test_unsupported_diff_not_silently_dropped(self):
        for lang, path in [('javascript', 'src/a.js'), ('typescript', 'src/a.ts'), ('go', 'main.go')]:
            with self.assertRaises(ValueError):
                parse_patch(f'diff --git a/{path} b/{path}\nold mode 100644\nnew mode 100755\n', lang)

    def test_mixed_dataset_rejected_before_measurement(self):
        with self.assertRaisesRegex(ValueError, 'one supported language'):
            list(analyze_submission({}, None, [dict(instance_id='a', language='python'),
                                               dict(instance_id='b', language='go')]))
        with self.assertRaisesRegex(ValueError, 'mixed measurement tracks'):
            leaderboard([{'measurement_track': None}, {'measurement_track': {'language': 'go'}}])


@unittest.skipUnless(HAS_LANGUAGES, 'optional grammar dependencies not installed')
class LanguageMeasurementTests(unittest.TestCase):
    def test_added_root_files_are_measured(self):
        for language, path, text in [('go', 'main.go', 'package main\nfunc main() {}\n'),
                                     ('javascript', 'index.js', 'const value = 1;\n'),
                                     ('typescript', 'index.ts', 'const value: number = 1;\n')]:
            m = measure(diff('', text, path), lambda _: '', language=language)
            self.assertGreater(m['units_added'], 0)
            self.assertEqual(m['units_deleted'], 0)
            self.assertEqual(m['files_changed'], 1)
            self.assertEqual(m['measurement_track']['language'], language)

    def test_formatting_value_changes_and_invalid_syntax(self):
        for language, path, before, formatted, changed in [
            ('javascript', 'src/a.js', 'const a=1;\n', '// comment\nconst a = 1;\n', 'const b=2;\n'),
            ('typescript', 'src/a.ts', 'const a:number=1;\n', '// c\nconst a: number = 1;\n', 'const b:number=2;\n'),
            ('go', 'a.go', 'package p\nvar a=1\n', 'package p\n// c\nvar a = 1\n', 'package p\nvar b=2\n')]:
            for after, changes in [(formatted, False), (changed, True)]:
                m = measure(diff(before, after, path), lambda _: before, language=language)
                self.assertEqual(m['churn'] > 0, changes)
                self.assertEqual(m['files_changed'], int(changes))
                self.assertEqual(m['net_units'], 0)
                self.assertEqual(m['structural_churn'], 0)
            with self.assertRaisesRegex(ValueError, 'invalid or recovered'):
                measure(diff(before, 'function {\n', path), lambda _: before, language=language)
            with self.assertRaisesRegex(ValueError, 'full-file'):
                measure(diff(before, changed, path), language=language)

    def test_generated_header_cannot_hide_changes(self):
        before = 'const a = 1;\n'
        after = '// Code generated by agent. DO NOT EDIT.\nconst a = 2;\n'
        m = measure(diff(before, after, 'src/a.js'), lambda _: before, language='javascript')
        self.assertGreater(m['churn'], 0)

    def test_failed_attempt_is_measured_and_track_recorded(self):
        source = 'package p\nvar x = 1\n'
        patch_text = diff(source, 'package p\nvar x = 2\n', 'main.go')
        submission = dict(agent='model', predictions={'task': patch_text}, resolved=set(), evaluated={'task'},
                          result_details={'unresolved': ['task']}, provenance={'prediction_url': 'https://example.org/'})
        dataset = [dict(instance_id='task', repo='org/repo', base_commit='abc', patch='', language='go')]
        with patch('parsimony.benchmark.base_source', return_value=lambda _: source):
            r, = analyze_submission(submission, None, dataset, include_failed=True)
        self.assertEqual(r['analysis_status'], 'ok')
        self.assertFalse(r['resolved'])
        self.assertGreater(r['metrics']['churn'], 0)
        self.assertEqual(r['measurement_track'], r['metrics']['measurement_track'])
