"""Adversarial patches: edits that should or should not move the coding-unit footprint.

Each case states the expected (net_units, churn). Known limitations are asserted
as current behavior so a change to them is deliberate; docs/adversarial-validation.md
explains each case and compares units with the pre-0.5 lexical-token metric.
"""
import difflib
import unittest

from parsimony.analysis import measure
from parsimony.scoring import out_of_scope

BASE = 'def area(width, height):\n    return width * height\n'
GUARDED = BASE.replace('    return width * height',
                       '    if width < 0 or height < 0:\n        raise ValueError(width, height)\n'
                       '    return width * height')
UNUSED = '\n\ndef unused(x):\n    if x:\n        return x + 1\n    return 0\n'


def diff(before, after, path='pkg/core.py', new_file=False):
    return ''.join(difflib.unified_diff(before.splitlines(True), after.splitlines(True),
                                       '/dev/null' if new_file else 'a/' + path, 'b/' + path))


def run(before, after, path='pkg/core.py', new_file=False):
    return measure(diff(before, after, path, new_file), lambda p: before)


# name: (before, after, path, (net_units, churn))
FREE = {
    'comments and blank lines': (BASE, '# Area.\n\ndef area(width, height):  # rectangle\n\n    return width * height\n'),
    'line wrapping, parentheses, trailing comma': (BASE, 'def area(\n    width,\n    height,\n):\n    return (width *\n            height)\n'),
    'quote style and implicit concatenation': ('x = "ab"\n', "x = 'a' 'b'\n"),
    'semicolon-joined statements': ('a = 1\nb = 2\n', 'a = 1; b = 2\n'),
    'tabs instead of spaces': ('if x:\n    y()\n', 'if x:\n\ty()\n'),
    'f-string spacing': ('s = f"{x}"\n', 's = f"{ x }"\n'),
    'docstring added': (BASE, BASE.replace(':\n', ':\n    """Rectangle area."""\n', 1)),
    'same literal value (255 vs 0xff)': ('x = 255\n', 'x = 0xff\n'),
}

COUNTED = {
    # Each renamed occurrence is one deleted and one added unit.
    'identifier-only rename': (BASE, BASE.replace('width', 'w'), (0, 4)),
    # Semantically equivalent, but units follow source order.
    'keyword arguments reordered': ('f(a=1, b=2)\n', 'f(b=2, a=1)\n', (0, 4)),
    # If, Compare, BoolOp, Compare, 4 names, 2 literals, Raise, Call, 3 names, EndBlock = 14.
    'guard clause added': (BASE, GUARDED, (14, 14)),
}


class AdversarialTests(unittest.TestCase):
    def test_formatting_and_comments_are_free(self):
        for name, (before, after) in FREE.items():
            with self.subTest(name):
                result = run(before, after)
                self.assertEqual((result['net_units'], result['churn']), (0, 0))
                self.assertEqual(result['files_changed'], 0)

    def test_counted_edits(self):
        for name, (before, after, expected) in COUNTED.items():
            with self.subTest(name):
                result = run(before, after)
                self.assertEqual((result['net_units'], result['churn']), expected)
        rename = run(*COUNTED['identifier-only rename'][:2])
        self.assertEqual(rename['structural_churn'], 0)  # diagnostic flags it as value-only

    def test_edits_confined_to_excluded_files(self):
        for path in ('tests/test_core.py', 'pkg/tests/test_core.py', 'docs/conf.py', 'pkg/conftest.py',
                     'setup.py', 'setup.cfg', 'pyproject.toml', 'tox.ini', 'examples/demo.py',
                     'testing/test_core.py'):
            with self.subTest(path):
                result = run(BASE, GUARDED, path)
                self.assertEqual((result['churn'], result['excluded_files']), (0, [path]))
                # Scoring treats an all-excluded patch as unmeasured, never as a free success.
                self.assertTrue(out_of_scope(result))

    def test_excluded_edits_do_not_hide_or_inflate_implementation(self):
        patch = diff(BASE, GUARDED) + diff(BASE, GUARDED + UNUSED * 20, 'tests/test_core.py')
        result = measure(patch, lambda p: BASE)
        self.assertEqual((result['net_units'], result['churn']), (14, 14))
        self.assertEqual(result['excluded_files'], ['tests/test_core.py'])
        self.assertFalse(out_of_scope(result))

    def test_generated_header_cannot_hide_an_edit(self):
        # 0.5.1: only the base commit's header marks a file as generated.
        tagged = run(BASE, '# Auto-generated file, do not edit.\n' + GUARDED)
        self.assertEqual((tagged['churn'], tagged['excluded_files']), (14, []))
        new_file = run('', '# This file is auto-generated.\n' + BASE, new_file=True)
        self.assertEqual(new_file['excluded_files'], [])
        self.assertGreater(new_file['churn'], 0)
        generated = '# Generated by protoc. DO NOT EDIT.\n' + BASE
        self.assertEqual(run(generated, generated + 'x = 1\n')['excluded_files'], ['pkg/core.py'])

    def test_nested_testing_package_is_implementation(self):
        # 0.5.1: sympy/testing/, lib/matplotlib/testing/ ship as library code.
        for path in ('sympy/testing/runtests.py', 'lib/matplotlib/testing/decorators.py'):
            with self.subTest(path):
                self.assertEqual(run(BASE, GUARDED, path)['churn'], 14)

    def test_backup_copy_diff_is_unmeasured(self):
        # Seen in DeepSeek V3.2 failed patches: `--- a/x.py.bak` / `+++ b/x.py`.
        patch = diff(BASE, GUARDED).replace('--- a/pkg/core.py', '--- a/pkg/core.py.bak')
        result = measure(patch, lambda p: self.fail('backup path fetched'))
        self.assertTrue(out_of_scope(result))

    def test_known_limitation_unrelated_deletion_earns_net_credit(self):
        # The analyzer cannot tell related from unrelated code: deleting an unused
        # function lowers net units. Churn (20% of the score) still charges for it,
        # and the net_floor=0 sensitivity variant removes the credit.
        result = run(BASE + UNUSED, BASE)
        self.assertEqual((result['net_units'], result['churn']), (-12, 12))

    def test_known_limitation_moved_code_counts_as_edits(self):
        before = 'def a():\n    return 1\n\n\ndef b():\n    return 2\n'
        after = 'def b():\n    return 2\n\n\ndef a():\n    return 1\n'
        result = run(before, after)
        self.assertEqual((result['net_units'], result['churn']), (0, 8))

    def test_known_limitation_hardcoded_test_input_is_cheaper(self):
        # Units measure size, not generality: special-casing the test's input costs
        # fewer units than the general fix.
        before = 'def f(items):\n    return items\n'
        general = 'def f(items):\n    valid = [item for item in items if item is not None]\n    return sorted(valid)\n'
        hardcoded = 'def f(items):\n    if items == [3, None, 1]:\n        return [1, 3]\n    return items\n'
        self.assertEqual(run(before, general)['churn'], 14)
        self.assertEqual(run(before, hardcoded)['churn'], 12)
